---

packages:
    - epel-release
    - bash-completion
    - bind-utils
    - bzip2
    - cloud-utils-growpart
    - curl
    - fio
    - firewalld
    - gdisk
    - gzip
    - iotop
    - iperf3
    - jq
    - lshw
    - lsof
    - lz4
    - nano
    - nc
    - net-tools
    - procps-ng
    - psmisc
    - rsync
    - tar
    - tcpdump
    - telnet
    - traceroute
    - tree
    - unzip
    - vim
    - wget