---

- name: dowload node_exporter
  get_url:
    url: "{{ node_exporter.url }}"
    dest: "{{ node_exporter.download }}"

- name: unpack node_exporter
  unarchive:
    src: "{{ node_exporter.download }}/node_exporter-{{ node_exporter.version }}.{{ node_exporter.architecture }}.tar.gz"
    dest: "{{ node_exporter.download }}"
    remote_src: yes

- name: copy files node_exporter
  copy:
    src: "{{ node_exporter.download }}/node_exporter-{{ node_exporter.version }}.{{ node_exporter.architecture }}/{{ item }}"
    dest: "{{ node_exporter.bin }}"
    owner: "{{ node_exporter.user }}"
    group: "{{ node_exporter.group }}"
    mode: 0755
    remote_src: yes
  when: __check_node_exporter_present.stat.exists == false or not __get_node_exporter_version.stdout == node_exporter_version

- name: install service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0755
  notify: reload_daemon_and_restart_node_exporter

- name: start node_exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes