---

- name: DNF update the system
  dnf:
    name:  "*"
    state: latest

- name: install epel repo
  dnf:
    name: epel-release
    state: present
    update_cache: yes

- name: install grafana
  dnf:
    name: "{{ grafana.dir }}/grafana-{{grafana.version}}.{{grafana.architecture}}.rpm"
    state: present
    update_cache: yes


- name: start grafana
  service:
    name: grafana-server
    enabled: true
    state: started

- name: Grafana configuration file copy
  template:
    src: "grafana.ini.j2"
    dest: "{{ grafana.dir }}/grafana.ini"
  notify:  Restart the Grafana service


- name: Check if Grafana is accessible
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200