- name: install the latest packages for firewalld
  import_role:
    name: os/packages
  vars:
    package_action: "present"
    package_name: "firewalld"

- name: Enable and unmask the firewalld
  systemd:
    name: "firewalld.service"
    daemon_reload: yes
    state: started
    masked: no
    enabled: yes


- name: "Open {{ firewall_ports }} for service ssh"
  firewalld:
    port: "{{ firewall_ports }}"
    permanent: yes
    immediate: yes
    state: enabled

#- name: configure firewalld
#  block:
#    - name: open ports
#      firewalld:
#        port: "{{ item }}"
#        permanent: yes
#        immediate: yes
#        state: enabled
#      loop:
#        - 9090/tcp
#        - 9093/tcp
#        - 9094/tcp
#        - 9094/udp
#        - 9100/tcp
#        - 3000/tcp
#
#    - name: Open http service
#      firewalld:
#        service: "{{ item  }}"
#        permanent: yes
#        immediate: yes
#        state: enabled
#      loop:
#            - "http"
#            - "https"
#
#    - name: Reload firewalld service
#      command: firewall-cmd --reload
#  when: "'firewalld.service' in ansible_facts.service"
#  ignore_errors: true
#












- name: "Open {{ firewall_ports }} for service ssh"
  firewalld:
    port: "{{ firewall_ports }}"
    permanent: yes
    immediate: yes
    state: enabled

